[package]
name = "ebay-watcher"
version = "0.1.0"
edition = "2024"

[dependencies]
base64 = "0.22.1"
chrono = "0.4.42"
dotenv = "0.15.0"
reqwest = { version = "0.12.25", features = ["json"] }
serde = "1.0.228"
serenity = "0.12.4"
tokio = { version = "1.47.0", features = ["full"] }
